name: Build and Release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Dependencies
      run: sudo apt-get update && sudo apt-get install -y cmake libncurses5-dev libncursesw5-dev

    - name: Setup CMake
      run: cmake -B build -S .

    - name: Build
      run: cmake --build build

    - name: Upload Build Artifact
      uses: actions/upload-artifact@v4
      with:
        name: snake_game_artifact
        path: build/snake_game  # Adjust this path to the compiled binary

    - name: Install GitHub CLI
      run: sudo apt-get install gh

    - name: Create Release
      id: create_release
      run: |
        gh auth login --with-token < ${{ secrets.GITHUB_TOKEN }}
        gh release create v1.0.0 build/snake_game --title "Release v1.0.0" --notes "Release notes for v1.0.0"
