name: Build and Release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Dependencies
      run: sudo apt-get update && sudo apt-get install -y cmake libncurses5-dev libncursesw5-dev

    - name: Setup CMake
      run: cmake -B build -S .

    - name: Build
      run: cmake --build build

    - name: Upload Build Artifact
      uses: actions/upload-artifact@v4
      with:
        name: snake_game_artifact
        path: build/snake_game  # Adjust this path to the compiled binary

    - name: Install GitHub CLI
      run: sudo apt-get install gh

    - name: Authenticate GitHub CLI
      run: gh auth login --with-token <<< "${{ secrets.GITHUB_TOKEN }}"

    - name: Get Latest Release Version
      id: get_latest_release
      run: |
        latest_release=$(gh release list --limit 1 --json tagName --jq '.[0].tagName')
        echo "Latest release: $latest_release"
        if [ -z "$latest_release" ]; then
          echo "No releases found. Starting with v0.0.0"
          echo "version=0.0.0" >> $GITHUB_ENV
        else
          # Extract the version number and increment it
          version_number=$(echo "$latest_release" | sed 's/^v//')
          IFS='.' read -r major minor patch <<< "$version_number"
          patch=$((patch + 1))
          new_version="v${major}.${minor}.${patch}"
          echo "New version: $new_version"
          echo "version=$new_version" >> $GITHUB_ENV
        fi

    - name: Create Release
      run: |
        gh release create ${{ env.version }} build/snake_game --title "Release ${{ env.version }}" --notes "Release notes for ${{ env.version }}"
