name: Build and Release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Dependencies
      run: sudo apt-get update && sudo apt-get install -y cmake libncurses5-dev libncursesw5-dev

    - name: Setup CMake
      run: cmake -B build -S .

    - name: Build
      run: cmake --build build

    - name: Upload Build Artifact
      uses: actions/upload-artifact@v3
      with:
        name: snake_game_artifact
        path: build/snake_game  # Adjust this path to the compiled binary

    - name: Create Release
      id: create_release
      uses: actions/github-script@v6
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const { data: release } = await github.rest.repos.createRelease({
            owner: context.repo.owner,
            repo: context.repo.repo,
            tag_name: 'v1.0.0',  // Change this to your version tag
            name: 'Release v1.0.0',  // Change this to your release name
            draft: false,
            prerelease: false
          });
          core.setOutput('upload_url', release.upload_url);
